# 簡介

### 程式依序為：載入library、讀取訓練資料、檢查缺失值、檢查離群值、檢查異常值、分割X、Y、分割train_split、建模、計算交叉驗證結果的平均值。

## 載入lib

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
from sklearn.model_selection import cross_validate
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,GradientBoostingClassifier
from sklearn.naive_bayes import CategoricalNB,ComplementNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split


import seaborn as sns

# 讀取 訓練資料

In [2]:
df = pd.read_csv('train.csv')
df

,ID,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,8773,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.4,2,3.0,11.0,3.0,7.0,2.0,0,0
1,6709,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,9,1.0,10.0,0.0,8.0,2.0,0,0
2,1463,9,301.000000,0,0.0,38,2621.621429,0.021212,0.044508,10.721172,0.0,8,1.0,10.0,0.0,14.0,2.0,0,0
3,4095,2,13.333333,0,0.0,105,2062.443592,0.012205,0.020276,0.000000,0.6,2,5.0,10.0,0.0,7.0,2.0,0,0
4,3346,0,0.000000,0,0.0,19,220.384849,0.010526,0.024642,0.000000,0.0,2,1.0,1.0,0.0,7.0,2.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,3758,0,0.000000,0,0.0,4,81.000000,0.000000,0.050000,0.000000,0.4,2,1.0,1.0,5.0,7.0,2.0,0,0
8096,4437,1,15.200000,2,62.6,84,4941.698611,0.017647,0.038706,0.000000,0.0,6,3.0,11.0,1.0,8.0,2.0,0,0
8097,7449,0,0.000000,0,0.0,25,701.883333,0.000000,0.023333,0.000000,0.0,6,1.0,10.0,0.0,4.0,2.0,0,0
8098,665,9,183.785714,1,90.0,95,3346.501984,0.002118,0.018656,5.932009,0.0,8,5.0,10.0,5.0,4.0,2.0,0,1
8099,552,3,49.750000,0,0.0,20,547.400794,0.000000,0.011688,15.065863,0.0,8,5.0,10.0,8.0,4.0,2.0,0,1

## miss values
## 統計缺失值

In [3]:
df.isna().sum()

ID                         0
Administrative             0
Administrative_Duration    0
Informational              0
Informational_Duration     0
ProductRelated             0
ProductRelated_Duration    1
BounceRates                0
ExitRates                  0
PageValues                 0
SpecialDay                 0
Month                      0
OperatingSystems           1
Browser                    1
Region                     1
TrafficType                1
VisitorType                1
Weekend                    0
Revenue                    0
dtype: int64

In [4]:
### 檢視缺失值資料
df[df.isna().any(axis=1)]

,ID,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
4316,7,6,999.000000,0,0.0,14,211.470238,0.001190,0.039521,0.0,0.0,8,NaN,10.0,1.0,5.0,2.0,0,0
5378,1,1,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.0,0.6,2,3.0,NaN,NaN,NaN,NaN,0,0
7838,5,7,245.333333,0,0.0,5,NaN,0.027273,0.051818,0.0,0.0,2,3.0,3.0,6.0,12.0,2.0,0,0

In [5]:
### 取出非缺失值資料
df1=df[df.notna().all(axis=1)]
df1

,ID,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,8773,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.4,2,3.0,11.0,3.0,7.0,2.0,0,0
1,6709,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,9,1.0,10.0,0.0,8.0,2.0,0,0
2,1463,9,301.000000,0,0.0,38,2621.621429,0.021212,0.044508,10.721172,0.0,8,1.0,10.0,0.0,14.0,2.0,0,0
3,4095,2,13.333333,0,0.0,105,2062.443592,0.012205,0.020276,0.000000,0.6,2,5.0,10.0,0.0,7.0,2.0,0,0
4,3346,0,0.000000,0,0.0,19,220.384849,0.010526,0.024642,0.000000,0.0,2,1.0,1.0,0.0,7.0,2.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,3758,0,0.000000,0,0.0,4,81.000000,0.000000,0.050000,0.000000,0.4,2,1.0,1.0,5.0,7.0,2.0,0,0
8096,4437,1,15.200000,2,62.6,84,4941.698611,0.017647,0.038706,0.000000,0.0,6,3.0,11.0,1.0,8.0,2.0,0,0
8097,7449,0,0.000000,0,0.0,25,701.883333,0.000000,0.023333,0.000000,0.0,6,1.0,10.0,0.0,4.0,2.0,0,0
8098,665,9,183.785714,1,90.0,95,3346.501984,0.002118,0.018656,5.932009,0.0,8,5.0,10.0,5.0,4.0,2.0,0,1
8099,552,3,49.750000,0,0.0,20,547.400794,0.000000,0.011688,15.065863,0.0,8,5.0,10.0,8.0,4.0,2.0,0,1

In [6]:
### 刪除ID
df1=df1.drop(columns=['ID'])
df1

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.4,2,3.0,11.0,3.0,7.0,2.0,0,0
1,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,9,1.0,10.0,0.0,8.0,2.0,0,0
2,9,301.000000,0,0.0,38,2621.621429,0.021212,0.044508,10.721172,0.0,8,1.0,10.0,0.0,14.0,2.0,0,0
3,2,13.333333,0,0.0,105,2062.443592,0.012205,0.020276,0.000000,0.6,2,5.0,10.0,0.0,7.0,2.0,0,0
4,0,0.000000,0,0.0,19,220.384849,0.010526,0.024642,0.000000,0.0,2,1.0,1.0,0.0,7.0,2.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,0,0.000000,0,0.0,4,81.000000,0.000000,0.050000,0.000000,0.4,2,1.0,1.0,5.0,7.0,2.0,0,0
8096,1,15.200000,2,62.6,84,4941.698611,0.017647,0.038706,0.000000,0.0,6,3.0,11.0,1.0,8.0,2.0,0,0
8097,0,0.000000,0,0.0,25,701.883333,0.000000,0.023333,0.000000,0.0,6,1.0,10.0,0.0,4.0,2.0,0,0
8098,9,183.785714,1,90.0,95,3346.501984,0.002118,0.018656,5.932009,0.0,8,5.0,10.0,5.0,4.0,2.0,0,1
8099,3,49.750000,0,0.0,20,547.400794,0.000000,0.011688,15.065863,0.0,8,5.0,10.0,8.0,4.0,2.0,0,1

# 檢查離群值（outlier）

In [7]:
df1.describe().T

,count,mean,std,min,25%,50%,75%,max
Administrative,8097.0,2.309003,3.311535e+00,0.0,0.000000,1.000000,4.000000,2.700000e+01
Administrative_Duration,8097.0,80.802419,1.798223e+02,0.0,0.000000,7.000000,91.888889,3.398750e+03
Informational,8097.0,0.498209,1.258284e+00,0.0,0.000000,0.000000,0.000000,2.400000e+01
Informational_Duration,8097.0,32.896484,1.352345e+02,0.0,0.000000,0.000000,0.000000,2.549375e+03
ProductRelated,8097.0,31.796468,4.496670e+01,0.0,7.000000,18.000000,38.000000,7.050000e+02
ProductRelated_Duration,8097.0,83135.989140,6.359881e+06,0.0,183.833333,599.000000,1462.450000,5.634924e+08
BounceRates,8097.0,0.020324,1.319578e-01,-11.0,0.000000,0.003200,0.016923,2.000000e-01
ExitRates,8097.0,0.042678,4.791996e-02,0.0,0.014286,0.025121,0.050000,2.000000e-01
PageValues,8097.0,5.746534,1.794355e+01,0.0,0.000000,0.000000,0.000000,2.879538e+02
SpecialDay,8097.0,0.060417,1.977529e-01,0.0,0.000000,0.000000,0.000000,1.000000e+00
Month,8097.0,4.806348,3.175732e+00,0.0,2.000000,4.000000,8.000000,1.300000e+01
OperatingSystems,8097.0,2.236013,1.654882e+00,0.0,1.000000,1.000000,3.000000,7.000000e+00
Browser,8097.0,7.783130,3.309824e+00,0.0,3.000000,10.000000,10.000000,1.200000e+01
Region,8097.0,2.684945,2.668698e+00,0.0,0.000000,2.000000,6.000000,8.000000e+00
TrafficType,8097.0,7.669137,3.907569e+00,0.0,4.000000,8.000000,12.000000,1.900000e+01
VisitorType,8097.0,1.847351,3.777609e-01,0.0,2.000000,2.000000,2.000000,2.000000e+00
Weekend,8097.0,0.253304,1.188272e+00,0.0,0.000000,0.000000,0.000000,1.000000e+02
Revenue,8097.0,0.157713,3.644939e-01,0.0,0.000000,0.000000,0.000000,1.000000e+00

In [8]:
# 找出前2筆 ，看似outlier
df1['ProductRelated_Duration'].sort_values(ascending=False).head(10)

408     5.634924e+08
3953    1.000000e+08
7397    6.397352e+04
2318    4.317123e+04
6998    2.484416e+04
2115    2.388881e+04
2363    2.334208e+04
7392    2.305010e+04
8079    2.185705e+04
4760    2.167224e+04
Name: ProductRelated_Duration, dtype: float64

# 檢查異常值

In [9]:
# 找出小於0的資料，比率小於0不合理
df1[df1['BounceRates']<0]

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
184,1,7.0,0,0.0,50,2330.727381,-1.0,0.031399,0.0,0.0,8,5.0,10.0,6.0,12.0,2.0,0,0
7147,0,0.0,1,1729.0,19,1401.083333,-11.0,0.050000,0.0,0.0,9,1.0,10.0,0.0,12.0,2.0,0,0

In [10]:
#  13月 不存在
df1['Month'].value_counts()

2     2202
8     1951
1     1265
9     1140
7      355
6      290
4      288
5      284
3      190
0      131
13       1
Name: Month, dtype: int64

In [11]:
# 標記是否存在100，不合理
df1['Weekend'].value_counts()

0      6145
1      1951
100       1
Name: Weekend, dtype: int64

In [12]:
df1[df1['Weekend']==100]

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
1666,0,0.0,0,0.0,22,2189.5,0.009524,0.028571,0.0,0.0,8,0.0,10.0,0.0,5.0,2.0,100,0

In [13]:
df2=df1.drop(index=[408,3953,184,7147,7714,1666])
df2

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.4,2,3.0,11.0,3.0,7.0,2.0,0,0
1,0,0.000000,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,9,1.0,10.0,0.0,8.0,2.0,0,0
2,9,301.000000,0,0.0,38,2621.621429,0.021212,0.044508,10.721172,0.0,8,1.0,10.0,0.0,14.0,2.0,0,0
3,2,13.333333,0,0.0,105,2062.443592,0.012205,0.020276,0.000000,0.6,2,5.0,10.0,0.0,7.0,2.0,0,0
4,0,0.000000,0,0.0,19,220.384849,0.010526,0.024642,0.000000,0.0,2,1.0,1.0,0.0,7.0,2.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8095,0,0.000000,0,0.0,4,81.000000,0.000000,0.050000,0.000000,0.4,2,1.0,1.0,5.0,7.0,2.0,0,0
8096,1,15.200000,2,62.6,84,4941.698611,0.017647,0.038706,0.000000,0.0,6,3.0,11.0,1.0,8.0,2.0,0,0
8097,0,0.000000,0,0.0,25,701.883333,0.000000,0.023333,0.000000,0.0,6,1.0,10.0,0.0,4.0,2.0,0,0
8098,9,183.785714,1,90.0,95,3346.501984,0.002118,0.018656,5.932009,0.0,8,5.0,10.0,5.0,4.0,2.0,0,1
8099,3,49.750000,0,0.0,20,547.400794,0.000000,0.011688,15.065863,0.0,8,5.0,10.0,8.0,4.0,2.0,0,1

In [14]:
# 標記轉型整數
df2.loc()[:,'OperatingSystems':'Revenue'] = df2.loc()[:,'OperatingSystems':'Revenue'].astype(int)
df2.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                        int64
OperatingSystems             int32
Browser                      int32
Region                       int32
TrafficType                  int32
VisitorType                  int32
Weekend                      int32
Revenue                      int32
dtype: object

In [15]:
# 檢查敘述統計資料
df2.describe().T

,count,mean,std,min,25%,50%,75%,max
Administrative,8091.0,2.309974,3.312422,0.0,0.000000,1.000000,4.000000,27.000000
Administrative_Duration,8091.0,80.816523,179.872842,0.0,0.000000,7.000000,91.861111,3398.750000
Informational,8091.0,0.498331,1.258677,0.0,0.000000,0.000000,0.000000,24.000000
Informational_Duration,8091.0,32.701005,133.961624,0.0,0.000000,0.000000,0.000000,2549.375000
ProductRelated,8091.0,31.802249,44.981306,0.0,7.000000,18.000000,38.000000,705.000000
ProductRelated_Duration,8091.0,1193.079277,1952.936206,0.0,183.687500,598.783333,1461.145833,63973.522230
BounceRates,8091.0,0.021821,0.047777,0.0,0.000000,0.003215,0.016926,0.200000
ExitRates,8091.0,0.042690,0.047935,0.0,0.014286,0.025121,0.050000,0.200000
PageValues,8091.0,5.750796,17.949520,0.0,0.000000,0.000000,0.000000,287.953793
SpecialDay,8091.0,0.060462,0.197819,0.0,0.000000,0.000000,0.000000,1.000000
Month,8091.0,4.804845,3.174428,0.0,2.000000,4.000000,8.000000,9.000000
OperatingSystems,8091.0,2.236312,1.654830,0.0,1.000000,1.000000,3.000000,7.000000
Browser,8091.0,7.782722,3.310246,0.0,3.000000,10.000000,10.000000,12.000000
Region,8091.0,2.685947,2.668754,0.0,0.000000,2.000000,6.000000,8.000000
TrafficType,8091.0,7.668273,3.907801,0.0,4.000000,8.000000,12.000000,19.000000
VisitorType,8091.0,1.847361,0.377764,0.0,2.000000,2.000000,2.000000,2.000000
Weekend,8091.0,0.241009,0.427722,0.0,0.000000,0.000000,0.000000,1.000000
Revenue,8091.0,0.157830,0.364604,0.0,0.000000,0.000000,0.000000,1.000000

In [16]:
# 檢視 Revenue 比例(類別不平衡)
df2['Revenue'].value_counts()

0    6814
1    1277
Name: Revenue, dtype: int64

In [17]:
X= df2.loc()[:,:'Weekend']
Y= df2.loc()[:,'Revenue']

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y,
                                                    test_size=0.3,
                                                    stratify=Y,
                                                    random_state=0
                                                   )

In [19]:
X_train

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend
5806,4,364.500000,0,0.0,27,955.525000,0.013333,0.022222,0.000000,0.0,8,5,10,6,8,2,1
5942,2,172.000000,0,0.0,61,3374.916667,0.001111,0.021389,0.000000,0.0,2,1,10,5,8,2,0
7321,0,0.000000,0,0.0,8,201.000000,0.000000,0.062500,0.000000,0.0,1,1,1,5,8,2,0
2196,4,185.000000,0,0.0,40,1694.750000,0.020513,0.031197,0.000000,0.0,1,1,10,1,8,2,0
34,1,58.500000,0,0.0,23,1033.000000,0.008333,0.037500,0.000000,0.0,9,1,10,6,4,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6257,0,0.000000,0,0.0,49,1384.016667,0.000000,0.011905,0.000000,0.0,1,1,10,0,4,2,0
7580,3,42.000000,0,0.0,24,1381.733333,0.031481,0.018778,0.000000,0.0,2,5,10,2,12,2,0
8077,11,344.100000,2,477.6,57,1475.608427,0.016418,0.030869,10.459770,0.0,7,3,3,6,8,2,0
2489,15,572.583333,2,37.5,318,13717.402050,0.004177,0.015643,45.155135,0.0,8,1,10,0,4,2,0
7117,2,94.000000,0,0.0,25,893.100000,0.000000,0.009615,0.000000,0.0,1,1,1,2,8,2,0

In [20]:
Y_train

5806    0
5942    0
7321    0
2196    0
34      0
       ..
6257    0
7580    0
8077    0
2489    1
7117    0
Name: Revenue, Length: 5663, dtype: int32

In [25]:
def model_score(Y_test, y_pred,model):
    tn, fp, fn, tp = confusion_matrix(Y_test, y_pred).ravel()
    df_report1 = pd.DataFrame( 
        [[accuracy_score(Y_test, y_pred),
          precision_score(Y_test, y_pred),
          recall_score(Y_test, y_pred),
          (tn/(tn+fp)),
          f1_score(Y_test, y_pred),
          tn, fp, fn, tp
          ]],index=[model])
    df_report1.columns = [
        'accuracy',
        'precision',
        'recall/Sensitivity',
        'Specificity ',
        'f1_score',
        'tn', 'fp', 'fn', 'tp'
    ]
    return df_report1

model_dict={'RandomForest':RandomForestClassifier(random_state=0, verbose=0),
            'GradientBoosting':GradientBoostingClassifier(random_state=0, verbose=0),
            'ExtraTrees':ExtraTreesClassifier(n_jobs=8,random_state=0, verbose=0),
            'KNN':KNeighborsClassifier(),
            'SVM':SVC(probability=True),
            'CategoricalNB':CategoricalNB(),
            'ComplementNB':ComplementNB()
}
scores_list=[]

for key in model_dict.keys():
    temp=model_dict[key]
    temp.fit(X_train, Y_train)
    Y_pred = temp.predict(X_test)
    model_score_temp = model_score(Y_test, Y_pred,key)
    model_score_temp['estimator'] = [temp]
    scores_list.append(model_score_temp)
        
model_dict

{'RandomForest': RandomForestClassifier(random_state=0),
 'GradientBoosting': GradientBoostingClassifier(random_state=0),
 'ExtraTrees': ExtraTreesClassifier(n_jobs=8, random_state=0),
 'KNN': KNeighborsClassifier(),
 'SVM': SVC(probability=True),
 'CategoricalNB': CategoricalNB(),
 'ComplementNB': ComplementNB()}

In [26]:
df_scores= pd.concat(scores_list)
df_scores

,accuracy,precision,recall/Sensitivity,Specificity,f1_score,tn,fp,fn,tp,estimator
RandomForest,0.892092,0.692063,0.569191,0.952567,0.624642,1948,97,165,218,"(DecisionTreeClassifier(max_features='auto', r..."
GradientBoosting,0.896623,0.703704,0.595300,0.953056,0.644979,1949,96,155,228,([DecisionTreeRegressor(criterion='friedman_ms...
ExtraTrees,0.888386,0.720472,0.477807,0.965281,0.574568,1974,71,200,183,"(ExtraTreeClassifier(random_state=209652396), ..."
KNN,0.850082,0.552486,0.261097,0.960391,0.354610,1964,81,283,100,KNeighborsClassifier()
SVM,0.842669,1.000000,0.002611,1.000000,0.005208,2045,0,382,1,SVC(probability=True)
CategoricalNB,0.834432,0.447514,0.211488,0.951100,0.287234,1945,100,302,81,CategoricalNB()
ComplementNB,0.869440,0.579710,0.626632,0.914914,0.602258,1871,174,143,240,ComplementNB()

In [29]:
df_predict = pd.DataFrame()
for model_str in  df_scores.index:
    print(model_str)
    temp   = df_scores[df_scores.index==model_str]['estimator'][0].predict(X_test)
    df_temp = pd.DataFrame(temp)
    y_pred = df_temp
    df_predict[model_str]=y_pred

RandomForest
GradientBoosting
ExtraTrees
KNN
SVM
CategoricalNB
ComplementNB

In [30]:
df_predict

,RandomForest,GradientBoosting,ExtraTrees,KNN,SVM,CategoricalNB,ComplementNB
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...
2423,0,0,0,0,0,0,0
2424,0,0,0,0,0,0,0
2425,0,0,0,0,0,0,0
2426,0,0,0,0,0,0,0
2427,0,0,0,0,0,0,0

In [31]:
df_predict['label']=Y_test.to_numpy()
df_predict

,RandomForest,GradientBoosting,ExtraTrees,KNN,SVM,CategoricalNB,ComplementNB,label
0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...
2423,0,0,0,0,0,0,0,0
2424,0,0,0,0,0,0,0,0
2425,0,0,0,0,0,0,0,0
2426,0,0,0,0,0,0,0,0
2427,0,0,0,0,0,0,0,0

In [36]:


model_score_list=[]
for model_str in  df_predict.columns[:-1]:
    model_score_list.append(model_score(df_predict['label'], df_predict[model_str],model_str))

In [37]:
df_model_score=pd.concat(model_score_list)
df_model_score

,accuracy,precision,recall/Sensitivity,Specificity,f1_score,tn,fp,fn,tp
RandomForest,0.892092,0.692063,0.569191,0.952567,0.624642,1948,97,165,218
GradientBoosting,0.896623,0.703704,0.595300,0.953056,0.644979,1949,96,155,228
ExtraTrees,0.888386,0.720472,0.477807,0.965281,0.574568,1974,71,200,183
KNN,0.850082,0.552486,0.261097,0.960391,0.354610,1964,81,283,100
SVM,0.842669,1.000000,0.002611,1.000000,0.005208,2045,0,382,1
CategoricalNB,0.834432,0.447514,0.211488,0.951100,0.287234,1945,100,302,81
ComplementNB,0.869440,0.579710,0.626632,0.914914,0.602258,1871,174,143,240